## Save data to the project and do some exploration if desired

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
%matplotlib inline

In [11]:
infile = 'https://covidtracking.com/api/us/daily.csv'
outfile = '../data/raw/covidtracking/us_historical.csv'

not going to merge in the numbers from the current day, but you can do so if you like

In [12]:
pd.read_csv('https://covidtracking.com/api/v1/us/current.csv')

,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,recovered,hash,lastModified,death,hospitalized,total,totalTestResults,posNeg,notes
0,392594,1661868,16557,39011,45562,9649,932,4007,229,17809,94b5ed933b6b46e089078d5c7ff3da863f20922c,4/7/2020,12621,45562,2071019,2054462,2054462,"NOTE: ""total"", ""posNeg"", ""hospitalized"" will b..."

get historical numbers

In [13]:
df = pd.read_csv(infile)

In [14]:
df.to_csv(outfile)

brief exploration

In [15]:
df.head()

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,death,hospitalized,total,totalTestResults,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200407,56,392594,1661868,16557,39011.0,45562.0,9649.0,932.0,4007.0,...,12621,45562.0,2071019,2054462,2054462,1941.0,394.0,106104.0,31263.0,137367.0
1,20200406,56,361331,1555764,17292,27675.0,45168.0,6607.0,971.0,2932.0,...,10680,45168.0,1934387,1917095,1917095,1182.0,3796.0,126040.0,29023.0,155063.0
2,20200405,56,332308,1429724,17307,23061.0,41372.0,5497.0,913.0,612.0,...,9498,41372.0,1779339,1762032,1762032,1184.0,2970.0,111672.0,26553.0,138225.0
3,20200404,56,305755,1318052,15573,22158.0,38402.0,5207.0,691.0,656.0,...,8314,38402.0,1639380,1623807,1623807,1352.0,2411.0,193178.0,33767.0,226945.0
4,20200403,56,271988,1124874,61980,19926.0,35991.0,4686.0,593.0,70.0,...,6962,35991.0,1458842,1396862,1396862,1178.0,3342.0,96225.0,32889.0,129114.0

In [23]:
df.describe()

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,death,hospitalized,total,totalTestResults,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
count,3.500000e+01,35.000000,35.000000,3.500000e+01,35.000000,14.000000,18.000000,13.000000,14.000000,14.000000,...,35.000000,18.000000,3.500000e+01,3.500000e+01,3.500000e+01,34.000000,34.000000,34.000000,34.000000,34.000000
mean,2.020033e+07,52.028571,90526.600000,4.188144e+05,20974.028571,15950.714286,22055.500000,4142.461538,1720.714286,638.071429,...,2172.114286,22055.500000,5.303150e+05,5.093410e+05,5.093410e+05,370.911765,1340.058824,48856.470588,11543.411765,60399.882353
std,3.587380e+01,9.173125,120981.281759,5.169323e+05,26432.429478,10054.926129,15513.388939,2272.871444,1298.663184,1235.800050,...,3470.543031,15513.388939,6.524033e+05,6.376321e+05,6.376321e+05,517.360396,1582.336553,47932.941128,11901.370286,59300.161413
min,2.020030e+07,14.000000,118.000000,7.480000e+02,103.000000,96.000000,1964.000000,1299.000000,74.000000,4.000000,...,10.000000,1964.000000,9.690000e+02,8.660000e+02,8.660000e+02,1.000000,0.000000,205.000000,47.000000,263.000000
25%,2.020031e+07,51.000000,1618.500000,1.082700e+04,901.500000,9024.250000,7134.750000,2456.000000,746.500000,55.250000,...,37.500000,7134.750000,1.334700e+04,1.244550e+04,1.244550e+04,9.250000,0.000000,3979.000000,547.750000,4555.750000
50%,2.020032e+07,56.000000,23197.000000,1.559090e+05,3327.000000,15229.500000,20852.000000,3837.000000,1191.500000,69.500000,...,272.000000,20852.000000,1.825740e+05,1.791060e+05,1.791060e+05,66.000000,492.000000,37658.000000,7423.000000,45081.000000
75%,2.020033e+07,56.000000,149795.500000,7.383070e+05,55376.500000,21600.000000,35155.500000,5207.000000,2560.000000,523.750000,...,2683.500000,35155.500000,9.535595e+05,8.881025e+05,8.881025e+05,499.000000,2941.750000,86712.500000,21308.500000,106478.750000
max,2.020041e+07,56.000000,392594.000000,1.661868e+06,65709.000000,39011.000000,45562.000000,9649.000000,4270.000000,4007.000000,...,12621.000000,45562.000000,2.071019e+06,2.054462e+06,2.054462e+06,1941.000000,4482.000000,193178.000000,33767.000000,226945.000000